# Generated by Django 3.0.8 on 2020-08-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='N/A', max_length=100, verbose_name='Model description')),
                ('category', models.CharField(default='N/A', max_length=20, verbose_name='Mode category')),
                ('band', models.CharField(default='N/A', max_length=29, verbose_name='Model band')),
                ('vendor', models.CharField(max_length=50, null=True, verbose_name='Model vendor')),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='Model')),
                ('comments', models.CharField(max_length=200, null=True, verbose_name='comments')),
                ('image_file', models.CharField(max_length=20, null=True, verbose_name='Image file')),
                ('status', models.CharField(max_length=20, null=True, verbose_name='Model status')),
                ('last_update', models.DateField()),
                ('inventorys_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
