# Generated by Django 3.0.8 on 2020-09-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
