# Generated by Django 3.0.8 on 2020-08-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200801_2112'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='inventorys_id',
            new_name='inventory_id',
        ),
    ]
