# Generated by Django 3.0.8 on 2020-08-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='N/A', max_length=50, verbose_name='Item Serial number')),
                ('model', models.CharField(default='N/A', max_length=50, verbose_name='Item Model ')),
                ('description', models.CharField(default='N/A', max_length=200, verbose_name='Item description')),
                ('location', models.CharField(default='N/A', max_length=100, verbose_name='Item location')),
                ('shelf', models.CharField(default='N/A', max_length=10, verbose_name='Item Shelf description')),
                ('category', models.CharField(default='N/A', max_length=50, verbose_name='Category')),
                ('status', models.CharField(default='N/A', max_length=50, verbose_name='Item status')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('remarks', models.CharField(default='N/A', max_length=500, null=True, verbose_name='Item remarks')),
                ('purchase_order', models.CharField(default='N/A', max_length=40, verbose_name='Item PO')),
                ('recieved_date', models.DateField(null=True)),
                ('shipped_date', models.DateField(null=True)),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Item  active')),
                ('last_update', models.DateField(null=True)),
                ('update_by', models.CharField(default='N/A', max_length=50, verbose_name='Item updated by')),
                ('model_id', models.IntegerField(null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('shelf_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('location', models.CharField(default='N/A', max_length=100, verbose_name='Item Serial number')),
                ('location_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('event_date', models.DateField(null=True)),
                ('operator', models.CharField(default='N/A', max_length=50, verbose_name='Item Serial number')),
                ('commen', models.CharField(default='N/A', max_length=500, verbose_name='Item Serial number')),
                ('location', models.CharField(default='N/A', max_length=50, verbose_name='Item Serial number')),
                ('mr', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('rma', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('inventorys_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
