# Generated by Django 3.0.8 on 2020-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('event_date', models.DateField(null=True)),
                ('operator', models.CharField(default='N/A', max_length=50, verbose_name='Item Serial number')),
                ('comment', models.CharField(default='N/A', max_length=500, verbose_name='Item Serial number')),
                ('locationname', models.CharField(default='N/A', max_length=50, verbose_name='Item Serial number')),
                ('mr', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('rma', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('inventory_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='N/A', max_length=50, verbose_name='serial number')),
                ('modelname', models.CharField(default='N/A', max_length=50, verbose_name='modelname')),
                ('description', models.CharField(default='N/A', max_length=200, verbose_name='description')),
                ('locationname', models.CharField(default='N/A', max_length=100, verbose_name='locationname')),
                ('shelf', models.CharField(default='N/A', max_length=10, verbose_name='shelf')),
                ('category', models.CharField(default='N/A', max_length=50, verbose_name='category')),
                ('status', models.CharField(default='N/A', max_length=50, verbose_name='status')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('remarks', models.CharField(default='N/A', max_length=500, null=True, verbose_name='remarks')),
                ('purchase_order', models.CharField(default='N/A', max_length=40, verbose_name='purchase_order')),
                ('recieved_date', models.DateField(null=True)),
                ('shipped_date', models.DateField(null=True)),
                ('active', models.BooleanField(default=True, null=True, verbose_name='active')),
                ('last_update', models.DateField(null=True)),
                ('update_by', models.CharField(default='N/A', max_length=50, verbose_name='update_by')),
                ('model_id', models.IntegerField(null=True)),
                ('location_id', models.IntegerField(null=True)),
                ('shelf_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='N/A', max_length=20, verbose_name='Item Serial number')),
                ('locationname', models.CharField(default='N/A', max_length=100, verbose_name='Item Serial number')),
                ('locationname_id', models.IntegerField(null=True)),
            ],
        ),
    ]
