# Generated by Django 3.0.8 on 2020-08-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='inventorys_id',
            new_name='inventory_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='location',
            new_name='locationname',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='model',
            new_name='modelname',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='location',
            new_name='locationname',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='location_id',
            new_name='locationname_id',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.AddField(
            model_name='inventory',
            name='locationname',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Item locationname'),
        ),
    ]
