# Generated by Django 3.0.8 on 2020-08-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200801_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='commen',
            new_name='comment',
        ),
    ]
