# Generated by Django 3.0.8 on 2020-09-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200913_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='field_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='repair_quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='site_quantity',
        ),
    ]
