# Generated by Django 3.0.8 on 2020-08-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200803_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='active',
            field=models.BooleanField(default=True, null=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='N/A', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='N/A', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='locationname',
            field=models.CharField(default='N/A', max_length=100, verbose_name='locationname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modelname',
            field=models.CharField(default='N/A', max_length=50, verbose_name='modelname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_order',
            field=models.CharField(default='N/A', max_length=40, verbose_name='purchase_order'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='remarks',
            field=models.CharField(default='N/A', max_length=500, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=50, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf',
            field=models.CharField(default='N/A', max_length=10, verbose_name='shelf'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='N/A', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='update_by',
            field=models.CharField(default='N/A', max_length=50, verbose_name='update_by'),
        ),
    ]
