# Generated by Django 3.0.8 on 2020-09-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200818_2117'),
        ('inventory', '0003_auto_20200916_1847'),
    ]

    operations = [
    ]
