# Generated by Django 3.0.8 on 2020-09-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_merge_20200917_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='rtv',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='recieved_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='N/A', max_length=50, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.CharField(default='N/A', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modelname',
            field=models.CharField(default='N/A', max_length=50, verbose_name='modelname'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(default='N/A', max_length=50, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shelf',
            field=models.CharField(default='N/A', max_length=10, verbose_name='shelf'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(default='N/A', max_length=50, verbose_name='status'),
        ),
    ]
