# Generated by Django 3.0.8 on 2020-08-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='location name')),
                ('address', models.CharField(default='N/A', max_length=100, verbose_name='location address')),
                ('city', models.CharField(default='N/A', max_length=50, verbose_name='location city')),
                ('state', models.CharField(default='N/A', max_length=25, verbose_name='locationstate')),
                ('phone', models.CharField(default='N/A', max_length=15, verbose_name='location Phone Number')),
                ('email', models.CharField(default='N/A', max_length=50, verbose_name='location Phone Number')),
                ('website', models.CharField(default='N/A', max_length=60, verbose_name='location Phone Number')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='location active')),
                ('image_file', models.CharField(max_length=50, null=True, verbose_name='location image')),
                ('created_on', models.DateField()),
                ('last_entry', models.DateField()),
                ('lat', models.FloatField(null=True, verbose_name='location Latitude')),
                ('lng', models.FloatField(null=True, verbose_name='location Longitude')),
                ('inventorys_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
