# Generated by Django 3.0.8 on 2020-08-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='shelf',
            field=models.CharField(default='N/A', max_length=25, verbose_name='shelf'),
        ),
    ]
